### ISSUE TITLE
请问你多个不同的norm具体指什么？

### ISSUE THREAD

**Issue by tzcsky** [GuoShi28/Caffe-Instance-Normalization-and-Guided-Instance-Normalization#1]
你好，请问你上传的多个不同版本的 instance norm分别是什么？
1. instance_norm
2. ins_norm
3. guided instance norm
我大致看了一下这三个是三个不同的人对instance norm实现吗？请问具体有什么区别吗？
谢谢你

**Comment by GuoShi28** [comment]
我把Readme更新了下，你看下是否可以解决你的问题，Ins_norm的文件我删掉了，是以前的版本，没有用。有其他的问题，可以再问我。 @limingjian
